GET http://localhost:8000/users HTTP/1.1
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqb2huZG9lNEBkb21haW4uY29tIiwicm9sZSI6IlVTRVIiLCJleHAiOjE3MTcxNzAyOTN9.Xeq3tz3yf1oLtYEVmlbw-b5rKsTYylvl9i4ajnHej1Q

###

GET http://localhost:8000/users/1 HTTP/1.1


###

POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "username": "johndoe5",
  "email": "johndoe4@domain.com",
  "password": "Password1@"
}

###

PUT http://localhost:8000/users/3 HTTP/1.1
Content-Type: application/json

{
  "username": "johndoethenewNEW",
  "email": "johndoethenewNEW@domain.com"
}

###

DELETE http://localhost:8000/users/4 HTTP/1.1
