GET http://127.0.0.1:8000/users/2/items HTTP/1.1

###

GET http://127.0.0.1:8000/users/1/items/2 HTTP/1.1

###

POST http://127.0.0.1:8000/users/1/items HTTP/1.1
content-type: application/json

{
    "id": 10,
    "name": "New item",
    "description": "New item description",
    "user_id": 1
}

###


PUT http://127.0.0.1:8000/users/1/items/1 HTTP/1.1
content-type: application/json

{
    "name": "Updated item",
    "description": "Updated item description"
}